// Frontend Course/Solution12/src/App.vue
<script lang="ts">
// Main store
interface task {
    id: string,
    text: string,
    done: boolean
}
let taskString = localStorage.getItem("tasks");
if(!taskString) {
    taskString = ""
}
const initialState = JSON.parse(taskString);
const tasks:task[] = initialState;

export default {
  data() {
      return {
          tasks: initialState,
          text: ""
      }
  },
  methods: {
      clear() {
          this.tasks.length = 0;
          localStorage.setItem("tasks", JSON.stringify(this.tasks));
      },
      input(id:string) {
          this.tasks.map((task:task) => {
              if(task.id == id) {
                  task.done = !task.done;
              }
          });
          localStorage.setItem("tasks", JSON.stringify(this.tasks));
      },
      add() {
        if(this.text=="") {   
          return;
        }
          let newTask:task = {
              id: new Date().getTime().toString(),
              text: this.text,
              done: false
          }
          this.text = "";
          this.tasks.push(newTask);
          localStorage.setItem("tasks", JSON.stringify(this.tasks));
      },
      delet(id:string) {
        const index = this.tasks.findIndex((task: task) => task.id === id);
        this.tasks.splice(index, 1);
        localStorage.setItem("tasks", JSON.stringify(this.tasks));
        }
      }, 
    computed : {
      count() {
        return this.tasks.length;
      }
    }
}
</script>

<template>
  <h1>To Do List</h1>
  <main id="wrapper">
      <div id="container"> 
        <div 
        v-for="(task) in tasks" 
        :id="task.id" 
        class="task"
        :key="task.id"
        >
          <p :class="{ 'task--crossed': task.done }">
            {{task.text}}
          </p>
          <div class="task__btns">
            <input class="task__check" type="checkbox" v-model="task.done" @change="input(task.id)"/>
            <button @click="delet(task.id)" class="task__button">X</button>
          </div>
        </div>
      </div>
      <div id="control-panel">
          <label id="control-panel__label" htmlFor="control-panel__controls">
            Add a new task to the list
          </label>
          <div id="control-panel__controls">
            <textarea 
            id="controls__textarea" placeholder="Write new task here:" autoFocus
            v-model="text"
            />
            <button id="controls__button" @click="add">+</button>
          </div>
      </div>
  </main>
  <p id="container__status">
    You currently have {{count}} tasks.
  </p>
  <button @click="clear" id="delete-all">Delete all tasks</button>
</template>

// Frontend Course/Solution11/src/App.tsx
import React, { useState, useEffect, useRef } from 'react'

interface Task {
  id: string,
  text: string,
  done: boolean
}

function App() {
  const [containerStatus, updateContainerStatus] = useState(0);

  let taskString = localStorage.getItem("tasks");
  if(!taskString) {
    taskString = ""
  }
  const initialState: Task[] = JSON.parse(taskString);

  const [taskList, updateTaskList] = useState<Task[]>(initialState);
  const [currentText, updateCurrentText] = useState("");

  const textarea = useRef<HTMLTextAreaElement>(null);

  const handleTextUpdate = (event: React.ChangeEvent<HTMLTextAreaElement>) => {
    updateCurrentText(event.target.value);
  }

  const handleClick = () => {
    if(currentText !== "") {
      let id = new Date().getTime().toString();
      let task: Task = {
        id: id,
        text: currentText,
        done: false
      };
      updateTaskList([...taskList, task]);
      updateCurrentText("");
    } else {
      textarea.current!.placeholder="You need to write your task here!";
      textarea.current!.style.border="1px solid red";
      setTimeout(()=> {
        textarea.current!.placeholder="Write new task here:";
        textarea.current!.style.border="1px solid gray";
      }, 2000)
    }
  }

  const handleDeleteAll = () => {
    updateTaskList([]);
  }

  const updateDone = (id:string):Task[] => {
    const newState: Task[] = taskList.map(task => {
      if(task.id === id) {
        return {...task, done: !task.done}
      } else return task;
    });
    return newState;
  }

  const handleInput = (event: React.ChangeEvent<HTMLInputElement>, task:Task) => {
    updateTaskList(updateDone(task.id));
  }

  const handleDeleteOne = (event: React.MouseEvent<HTMLButtonElement>, input:Task) => {
    const newState:Task[] = taskList.filter(task => {
      if(task.id !== input.id) {
        return task;
      }
    });
    updateTaskList(newState);
  }

  useEffect(() => {
    updateContainerStatus(taskList.length);
    localStorage.setItem("tasks", JSON.stringify(taskList))
  }, [taskList])

  return (
    <>
      <h1>To Do List</h1>
      <main id="wrapper">
          <div id="container">
            {
              taskList.map((task) => {
                return <div id={task.id} key={task.id} className = 'task'>
                  <p style={{textDecoration: task.done ? "line-through" : "none"}}>{task.text}</p>
                  <div className="task__btns">
                    <input className="task__check" type="checkbox" onChange={(e) => handleInput(e, task)} checked={task.done}/>
                    <button className="task__button" onClick={(e) => handleDeleteOne(e, task)}>X</button>
                  </div>
                </div>
              })
            }
          </div>
          <div id="control-panel">
              <label id="control-panel__label" htmlFor="control-panel__controls">Add a new task to the list</label>
              <div id="control-panel__controls">
                  <textarea id="controls__textarea" placeholder="Write new task here:" value={currentText} onChange={handleTextUpdate} ref={textarea} autoFocus/>
                  <button onClick={handleClick} id="controls__button">+</button>
              </div>
          </div>
      </main>
      <p id="container__status">{containerStatus} tasks</p>
      <button id="delete-all" onClick={handleDeleteAll}>Delete All</button>
    </>
  )
}
export default App;
